%YAML:1.0
---
# Camera Parameters
SerialNumber: "DB0498485"
TopicName: "left_camera/image"

# 0: Off (free-run), 1: On (hardware trigger via LINE0)
TriggerEnable: 1

# 0: Off, 1: Once, 2: Continues
ExposureAutoMode: 0
ExposureTime: 15000

image_scale: 0.5
# 0: Off, 1: Once, 2: Continues
GainAuto: 2
Gain: 15
Gamma: 0.7
# 0: user, 1: sRGB
GammaSelector: 1

# 0: RGB8, 1: BayerRG8, 2: BayerRG12Packed, 3: BayerGB12Packed, 4: BayerGB8
PixelFormat: 0
