#ifndef HARD_SYNC_VERSION_H_
#define HARD_SYNC_VERSION_H_

#define HARD_SYNC_VERSION_MAJOR (0u)
#define HARD_SYNC_VERSION_MINOR (1u)
#define HARD_SYNC_VERSION_PATCH (0u)

#endif  // HARD_SYNC_VERSION_H_
